# Generated by Django 4.0.3 on 2022-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_alter_searchrecord_count_of_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrecord',
            name='time_spent',
            field=models.BigIntegerField(default=0),
        ),
    ]
